const KEY='rmLocator.v1';
const sample=[
{id:crypto.randomUUID(),canonicalName:'Carbomer 940',aliases:['Synthalen-K','Acritamer 940','Lubrizol Viscosity Booster 940'],itemCode:'SAMPLE-RM-001',vendor:'Sample record',stocks:[{location:'G26',qty:22,unit:'kg'},{location:'G27',qty:8,unit:'kg'}]},
{id:crypto.randomUUID(),canonicalName:'Glycerin',aliases:['Glycerol','Vegetable Glycerin'],itemCode:'SAMPLE-RM-002',vendor:'Sample record',stocks:[{location:'A11',qty:55,unit:'kg'}]}
];
let inv=load();
function load(){try{const x=localStorage.getItem(KEY);if(x)return JSON.parse(x);localStorage.setItem(KEY,JSON.stringify(sample));return structuredClone(sample)}catch{return structuredClone(sample)}}
function save(){localStorage.setItem(KEY,JSON.stringify(inv));renderInv();doSearch()}
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
const norm=s=>String(s??'').toLowerCase().replace(/[^a-z0-9]+/g,' ').trim();
function matches(q){q=norm(q);if(!q)return[];return inv.map(m=>{let score=0;[m.canonicalName,...(m.aliases||[]),m.itemCode,m.vendor].filter(Boolean).map(norm).forEach((f,i)=>{if(f===q)score=Math.max(score,i?95:100);else if(f.startsWith(q))score=Math.max(score,i?80:85);else if(f.includes(q))score=Math.max(score,i?65:70);else if(q.split(' ').every(w=>f.includes(w)))score=Math.max(score,55)});return{m,score}}).filter(x=>x.score).sort((a,b)=>b.score-a.score).map(x=>x.m)}
const units={g:['m',1],kg:['m',1000],lb:['m',453.59237],oz:['m',28.349523125],mL:['v',1],L:['v',1000],gal:['v',3785.411784],'fl oz':['v',29.5735295625],ea:['c',1]};
function conv(q,f,t){if(!units[f]||!units[t]||units[f][0]!==units[t][0])return null;return q*units[f][1]/units[t][1]}
function fmt(n){return Number(Number(n).toFixed(3)).toLocaleString()}
function stockHtml(m){return m.stocks?.length?m.stocks.map(s=>`<span class="badge">${esc(s.location)} · ${fmt(Number(s.qty)||0)} ${esc(s.unit)}</span>`).join(' '):'<span class="badge warn">No locations</span>'}
function card(m,edit=false){return `<article class="card" ${edit?`data-edit="${esc(m.id)}"`:''}><div class="title">${esc(m.canonicalName)}</div><div class="aliases">${m.aliases?.length?'aka '+esc(m.aliases.join(', ')):'No aliases entered'}</div>${m.itemCode?`<p class="small"><b>Item:</b> ${esc(m.itemCode)}</p>`:''}${m.vendor?`<p class="small"><b>Vendor:</b> ${esc(m.vendor)}</p>`:''}<div class="row">${stockHtml(m)}</div></article>`}
for(const b of document.querySelectorAll('.tab'))b.onclick=()=>{document.querySelectorAll('.tab').forEach(x=>x.classList.toggle('active',x===b));document.querySelectorAll('.panel').forEach(p=>p.classList.toggle('active',p.id===b.dataset.tab))};
const search=document.querySelector('#search'),results=document.querySelector('#results');
search.oninput=doSearch;
function doSearch(){const q=search.value.trim();results.innerHTML=!q?'<div class="empty">Type a chemical name, brand name, vendor, or item code.</div>':matches(q).map(m=>card(m)).join('')||'<div class="empty">No matching material found.</div>'}
const filter=document.querySelector('#filter'),invList=document.querySelector('#invList');
filter.oninput=renderInv;
function renderInv(){const q=norm(filter.value);const a=inv.filter(m=>!q||norm([m.canonicalName,...(m.aliases||[]),m.itemCode,m.vendor].join(' ')).includes(q)).sort((a,b)=>a.canonicalName.localeCompare(b.canonicalName));invList.innerHTML=a.map(m=>card(m,true)).join('')||'<div class="empty">No inventory records.</div>'}
invList.onclick=e=>{const a=e.target.closest('[data-edit]');if(a)openDlg(a.dataset.edit)};
const dlg=document.querySelector('#dlg'),stocks=document.querySelector('#stocks'),tpl=document.querySelector('#stockTpl');
function stockRow(s={location:'',qty:'',unit:'kg'}){const n=tpl.content.firstElementChild.cloneNode(true);n.querySelector('.loc').value=s.location||'';n.querySelector('.qty').value=s.qty??'';n.querySelector('.unit').value=s.unit||'kg';n.querySelector('.rem').onclick=()=>n.remove();stocks.append(n)}
function openDlg(id=null){const m=id?inv.find(x=>x.id===id):null;document.querySelector('#dlgTitle').textContent=m?'Edit material':'Add material';document.querySelector('#id').value=m?.id||'';document.querySelector('#name').value=m?.canonicalName||'';document.querySelector('#aliases').value=(m?.aliases||[]).join(', ');document.querySelector('#item').value=m?.itemCode||'';document.querySelector('#vendor').value=m?.vendor||'';stocks.innerHTML='';(m?.stocks?.length?m.stocks:[{}]).forEach(stockRow);document.querySelector('#delete').classList.toggle('hidden',!m);dlg.showModal()}
document.querySelector('#add').onclick=()=>openDlg();document.querySelector('#addStock').onclick=()=>stockRow();document.querySelector('#close').onclick=document.querySelector('#cancel').onclick=()=>dlg.close();
document.querySelector('#form').onsubmit=e=>{e.preventDefault();const id=document.querySelector('#id').value||crypto.randomUUID(),canonicalName=document.querySelector('#name').value.trim();if(!canonicalName)return;const aliases=document.querySelector('#aliases').value.split(/[,;\n]/).map(x=>x.trim()).filter(Boolean);const ss=[...stocks.querySelectorAll('.stock')].map(r=>({location:r.querySelector('.loc').value.trim().toUpperCase(),qty:Number(r.querySelector('.qty').value||0),unit:r.querySelector('.unit').value})).filter(s=>s.location);const rec={id,canonicalName,aliases,itemCode:document.querySelector('#item').value.trim(),vendor:document.querySelector('#vendor').value.trim(),stocks:ss};const i=inv.findIndex(x=>x.id===id);i>=0?inv[i]=rec:inv.push(rec);save();dlg.close()};
document.querySelector('#delete').onclick=()=>{const id=document.querySelector('#id').value,m=inv.find(x=>x.id===id);if(m&&confirm(`Delete ${m.canonicalName}?`)){inv=inv.filter(x=>x.id!==id);save();dlg.close()}};
function total(m,u){let n=0,ok=false,bad=0;(m.stocks||[]).forEach(s=>{const x=conv(Number(s.qty)||0,s.unit,u);if(x===null)bad++;else{n+=x;ok=true}});return{n,ok,bad}}
document.querySelector('#check').onclick=()=>{const reqs=document.querySelector('#batchIn').value.split(/\r?\n/).map(x=>x.trim()).filter(Boolean).map(line=>{const p=line.split(/\t|\||,/).map(x=>x.trim());return{name:p[0],qty:p[1]===''||p[1]===undefined?null:Number(p[1]),unit:p[2]||null}});let out='',enough=0,short=0,missing=0,review=0;for(const r of reqs){const m=matches(r.name)[0];if(!m){missing++;out+=`<article class="card"><div class="title">${esc(r.name)}</div><span class="badge bad">NOT FOUND</span></article>`;continue}let status,detail='';if(r.qty===null||!r.unit||Number.isNaN(r.qty)){review++;status='<span class="badge warn">LOCATION ONLY</span>'}else if(!units[r.unit]){review++;status='<span class="badge warn">CHECK UNIT</span>'}else{const t=total(m,r.unit);if(!t.ok){review++;status='<span class="badge warn">CHECK UNITS</span>'}else if(t.n>=r.qty){enough++;status='<span class="badge ok">ENOUGH</span>';detail=`<p><b>Required:</b> ${fmt(r.qty)} ${esc(r.unit)} · <b>Available:</b> ${fmt(t.n)} ${esc(r.unit)}</p>`}else{short++;status=`<span class="badge bad">SHORT ${fmt(r.qty-t.n)} ${esc(r.unit)}</span>`;detail=`<p><b>Required:</b> ${fmt(r.qty)} ${esc(r.unit)} · <b>Available:</b> ${fmt(t.n)} ${esc(r.unit)}</p>`}}out+=`<article class="card"><div class="title">${esc(r.name)} → ${esc(m.canonicalName)}</div><div class="aliases">${m.aliases?.length?'aka '+esc(m.aliases.join(', ')):''}</div><div class="row">${status}</div>${detail}<div class="row">${stockHtml(m)}</div></article>`}document.querySelector('#summary').innerHTML=reqs.length?`<div class="row"><span class="badge ok">${enough} enough</span><span class="badge bad">${short} short</span><span class="badge bad">${missing} not found</span><span class="badge warn">${review} review</span></div>`:'';document.querySelector('#batchOut').innerHTML=out||'<div class="empty">Enter batch materials above.</div>'};
document.querySelector('#clear').onclick=()=>{document.querySelector('#batchIn').value='';document.querySelector('#summary').innerHTML='';document.querySelector('#batchOut').innerHTML=''};
function dl(name,text,type){const u=URL.createObjectURL(new Blob([text],{type})),a=document.createElement('a');a.href=u;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(u),500)}
document.querySelector('#exportJson').onclick=()=>dl('raw-material-inventory.json',JSON.stringify({version:1,inventory:inv},null,2),'application/json');
document.querySelector('#importJson').onchange=async e=>{try{const d=JSON.parse(await e.target.files[0].text()),a=Array.isArray(d)?d:d.inventory;if(!Array.isArray(a))throw 0;if(confirm(`Replace inventory with ${a.length} records?`)){inv=a.map(m=>({...m,id:m.id||crypto.randomUUID()}));save()}}catch{alert('Invalid JSON backup')}e.target.value=''};
const csvCell=v=>'"'+String(v??'').replaceAll('"','""')+'"';
document.querySelector('#exportCsv').onclick=()=>{const rows=[['Canonical Name','Aliases','Item Code','Vendor','Location','Quantity','Unit'].map(csvCell).join(',')];inv.forEach(m=>(m.stocks?.length?m.stocks:[{}]).forEach(s=>rows.push([m.canonicalName,(m.aliases||[]).join('; '),m.itemCode||'',m.vendor||'',s.location||'',s.qty??'',s.unit||''].map(csvCell).join(','))));dl('raw-material-inventory.csv',rows.join('\n'),'text/csv')};
function parseCsv(t){let rows=[],row=[],cell='',q=false;for(let i=0;i<t.length;i++){const c=t[i],n=t[i+1];if(q){if(c==='"'&&n==='"'){cell+='"';i++}else if(c==='"')q=false;else cell+=c}else if(c==='"')q=true;else if(c===','){row.push(cell);cell=''}else if(c==='\n'){row.push(cell);rows.push(row);row=[];cell=''}else if(c!=='\r')cell+=c}row.push(cell);if(row.some(Boolean))rows.push(row);return rows}
document.querySelector('#importCsv').onchange=async e=>{try{const rows=parseCsv(await e.target.files[0].text()),h=rows[0].map(norm),idx=x=>h.indexOf(norm(x)),map=new Map();for(const r of rows.slice(1)){const n=(r[idx('Canonical Name')]||'').trim();if(!n)continue;const k=norm(n);if(!map.has(k))map.set(k,{id:crypto.randomUUID(),canonicalName:n,aliases:(r[idx('Aliases')]||'').split(';').map(x=>x.trim()).filter(Boolean),itemCode:(r[idx('Item Code')]||'').trim(),vendor:(r[idx('Vendor')]||'').trim(),stocks:[]});const loc=(r[idx('Location')]||'').trim().toUpperCase();if(loc)map.get(k).stocks.push({location:loc,qty:Number(r[idx('Quantity')]||0),unit:(r[idx('Unit')]||'kg').trim()||'kg'})}const a=[...map.values()];if(confirm(`Replace inventory with ${a.length} materials?`)){inv=a;save()}}catch{alert('Could not import CSV')}e.target.value=''};
renderInv();doSearch();if('serviceWorker'in navigator)addEventListener('load',()=>navigator.serviceWorker.register('sw.js').catch(()=>{}));
